language: elixir
elixir:
  - 1.5
  - 1.6
otp_release:
  - 18.0
  - 19.0
  - 20.0
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.0
sudo: false
before_script:
  - epmd -daemon
  - mix deps.get --only test
  - MIX_ENV=test mix compile
script:
  - mix test
  - if mix help | grep -c 'mix format' &> /dev/null; then mix format --check-formatted; fi
